apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
    - name: girus
      image: ubuntu
      args:
        - sleep
        - infinity
      volumeMounts:
        - name: primeiro-volume
          mountPath: /giropops
  volumes:
    - name: primeiro-volume
      emptyDir:
        sizeLimit: 256Mi
